version: '3.8'

services:
  backend:
    image: emivnajera/backend_p1_201903848
    build: ./backend
    container_name: backend
    ports:
      - 4000:4000
  frontend:
    image: emivnajera/frontend_p1_201903848
    build: ./frontend
    container_name: frontend
    ports:
    - 3000:3000
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
  db:
    image: mongo
    volumes:
      - ./database:/data/db



